#!/usr/bin/env bash
# transfer a file from our client to a server.

if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    PATH_TO_FILE=$1
    IP=$2
    USERNAME=$3
    PATH_TO_SSH_KEY=$4

fi

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

if [ $? -ne 0 ]; then
    exit 1
fi