#!/usr/bin/env bash
set -e  # Exit if any command fails

# Install Nginx
sudo apt update -y
sudo apt install -y nginx

# Start Nginx
sudo service nginx start

# Add the redirection rule for /redirect_me to the Nginx config
sed -i "/^}$/i \    location /redirect_me {\n        return 301 https://www.example.com;\n    }" /etc/nginx/sites-available/default

# Test and restart Nginx
sudo service nginx restart

