#!/usr/bin/env bash
# Exit script on any error
set -e

# Update system and install NGINX
sudo apt -y update
sudo apt -y install nginx

# Start NGINX service
sudo service nginx start

# Create a default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a custom 404 page
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/404.html > /dev/null

# Ensure correct permissions
sudo chmod 644 /usr/share/nginx/html/404.html

# Modify NGINX configuration to use the custom 404 page
sudo sed -i "/^}$/i \
    \n\terror_page 404 /404.html;\
    \n\tlocation = /404.html {\
    \n\t\troot /usr/share/nginx/html;\
    \n\t\tinternal;\
    \n\t}" /etc/nginx/sites-available/default

# Test and apply configuration
sudo nginx -t
sudo service nginx restart
