#!/usr/bin/env bash


sudo apt -y update
sudo apt -y upgrade

sudo apt -y install haproxy

sudo echo -e 'frontend otmaneks.tech\n\tbind *:80\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 531124-web-01 100.25.110.154:80 check\n\tserver 531124-web-01 100.25.110.154:80 check\n' >> /etc/haproxy/haproxy.cfg
sudo sed -i "9i ENABLED=1" /etc/default/haproxy

sudo service haproxy restart
