#!/usr/bin/env bash

# everything is about networking

# Check if script is run as root
if [ "$(id -u)" != "0" ]; then
    echo "This script requires root privileges to run."
    exit 1
fi

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# List TCP and UDP listening ports
netstat -tuln | awk '$NF=="LISTEN" {print $0}'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# List UNIX domain sockets listening ports
netstat -lx | awk '$1~/unix/ && $5=="LISTEN" {print $0}'