#!/usr/bin/env bash
# Infinite loop

echo $$ > /tmp/to_infinity_and_beyond_pid

trap 'rm -f /tmp/to_infinity_and_beyond_pid; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
