#!/usr/bin/env bash
# This script displays its own PID

# Use the ps command with appropriate options to display process information

PID=$(pgrep -f '4-to_infinity_and_beyond')

if [ -n "$PID" ]; then
    kill "$PID"
fi
