#!/usr/bin/env bash
# Printing filenames

filenames=()

for file in *; do
    if [ -f "$file" ]; then
        filename="${file#*[0-9]-}"
        filenames+=("$filename")
    fi
done

for filename in "${filenames[@]}"; do
    echo "$filename"
done
